### ISSUE TITLE
Getting error  'NoneType' object is not callable

### ISSUE THREAD

**Issue by doubledrat** [eclipse/paho.mqtt.python#503] opened 2020-07-26 09:02 UTC
not all the time, but sometimes getting this error -

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3428, in _thread_main
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1782, in loop_forever
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1193, in loop
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1588, in loop_write
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

```

my code is simple -

```
import paho.mqtt.client as mqtt
client=mqtt.Client("MQTTMonitor2")
client.connect("192.168.0.9")
client.on_message=on_message
client.loop_start()
client.subscribe("#",2)
signal.pause() # wait for a signal
```

let me know if my on_message code is relevant.  I'm assuming it's not as the error is in client.py

**Comment by MattBrittan** [comment] 2023-12-26 01:08
Sorry that no one has commented until now. Due to the age of this issue (possible the issue is already fixed or you have found a solution yourself) I'm going to close it (trying to get issues down to a manageable number).

If you are still having issues then please feel free to reopen. However I'd appreciate it if you could confirm which version of the library you are using (this makes it a lot easier to work out what's at line 1588 in `client.py`).

**Closed by MattBrittan** 2023-12-26 01:08 UTC
