### ISSUE TITLE
Connect with keepalive 0 reports BlockingIOError

### ISSUE THREAD

**Issue by InventoryTech** [eclipse/paho.mqtt.python#473] opened 2020-03-11 00:34 UTC
I'm attempting to connect with keepalive set to 0, I get the following error:

> Traceback (most recent call last):
>   File "main.py", line 55, in <module>
>     res = client.connect(broker_address, port=1883, keepalive=0, bind_address="")
>   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
>     return self.reconnect()
>   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
>     sock = self._create_socket_connection()
>   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
>     return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
>   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
>     raise err
>   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
>     sock.connect(sa)
> BlockingIOError: [Errno 115] Operation now in progress

My current understanding is that keepalive 0 is valid and should prevent keepalive pings being sent from the client to the broker?

**Comment by MattBrittan** [comment] 2024-01-07 02:41
I've tested this with the latest client (and Mosquitto 2.0.17) and was unable to duplicate. Due to the age of the issue I'm going to assume that the issue has been fixed in releases since this was raised (apologies it's taken so long for anyone to respond).

If this is still an issue, then please feel free to reopen (ideally with a reproducible example).

Note that some brokers will not accept a 0 keepalive without configuration (e.g. for mosquitto set `max_keepalive 0`).

**Closed by MattBrittan** 2024-01-07 02:41 UTC
