### ISSUE TITLE
Issues with reconnecting after upgrading to 1.3.0

### ISSUE THREAD

**Issue by oh5fsz** [eclipse/paho.mqtt.python#208] opened 2017-07-13 06:02 UTC
After upgrading the library to 1.3.0 we started to get issues with the library's reconnection feature. Frequently during reconnection the library raises the following exception:

> 13.07.17 07:32:40 (+0300) [Errno 32] Broken pipe
13.07.17 07:32:40 (+0300) Exception in thread Thread-3:
13.07.17 07:32:40 (+0300) Traceback (most recent call last):
13.07.17 07:32:40 (+0300)   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
13.07.17 07:32:40 (+0300)     self.run()
13.07.17 07:32:40 (+0300)   File "/usr/lib/python3.4/threading.py", line 868, in run
13.07.17 07:32:40 (+0300)     self._target(*self._args, **self._kwargs)
13.07.17 07:32:40 (+0300)   File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 2606, in _thread_main
13.07.17 07:32:40 (+0300)     self.loop_forever(retry_first_connection=True)
13.07.17 07:32:40 (+0300)   File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 1470, in loop_forever
13.07.17 07:32:40 (+0300)     rc = self.loop(timeout, max_packets)
13.07.17 07:32:40 (+0300)   File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 995, in loop
13.07.17 07:32:40 (+0300)     rc = self.loop_read(max_packets)
13.07.17 07:32:40 (+0300)   File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 1273, in loop_read
13.07.17 07:32:40 (+0300)     rc = self._packet_read()
13.07.17 07:32:40 (+0300)   File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 1773, in _packet_read
13.07.17 07:32:40 (+0300)     command = self._sock.recv(1)
13.07.17 07:32:40 (+0300) AttributeError: 'NoneType' object has no attribute 'recv'

We currently don't have any custom on_disconnect() -function and the loop_start() is ran from a thread and the connection uses SSL.

**Comment by PierreF** [comment] 2017-07-14 14:51
I can't reproduce this issue.

By looking at the code and your error:
* self._sock is None when error occur
* self._sock is NOT none at the beginning of loop_read
* I only see self._sock being set to None during handling_connack & if there is a protocol downgrade. And it's during reconnect which re-set self._sock to a valid socket. (this hold true if no user callback close the connection).

Some additional information may help:
* You said it's the reconnect feature that cause this issue, what may you think so ?
* In your callback (on_message, on_connect, on_...) are you calling anything that may close the socket (reconnect, reinitialise, disconnect) ?
* From another thread, are you calling anything that may close the socket ? or any loop_* method ?

**Comment by oh5fsz** [comment] 2017-07-17 05:58
The error doesn't appear on devices that have a stable connection. It seems to occur only on clients that are connected with an unstable connection like 3G or WLAN.

We removed all custom reconnection logic while upgrading to 1.3.0 since the plan was to test the improved reconnection handling introduced in 1.3.0. There's no custom on_disconnect-function and no reconnect is called from the on_message-function.

The MQTT object/thread is passed to other threads but they only use a function that calls publish. No loop methods or anything that should set the socket to None.

**Comment by PierreF** [comment] 2017-08-23 08:18
Got the same issue with the usage of publish.multiple() (thus no user callback may interfere).
I don't have much more information on how to reproduce. I can said that:

* publish.multiple was called with multiple messages, but when error occurred all message were sent (the list passed as argument was empty, e.g. publish.multiple had .pop() all messages)
* It is possible that the number of messages was large (in number, not in size)
* It is using SSL
* It is using a "slow" connection (from Asia to Europe, so latency is high)

The stack trace was:
```
AttributeError: 'NoneType' object has no attribute 'recv'
  File "celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "bleemeo_probe/tasks.py", line 860, in mqtt_send
    tls=tls_config,
  File "paho/mqtt/publish.py", line 153, in multiple
    client.loop_forever()
  File "paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "paho/mqtt/client.py", line 1773, in _packet_read
    command = self._sock.recv(1)
```

Interesting value of variables:
* In the function loop, socklist is [ [<ssl.SSLSocket [closed] fd=-1...>], [], []]
* In the function loop_read, max_packets is 22 and _ (the loop iteration variable) is 2

So loop_read seems to be called with a closed socket and loop_read fail at the second loop.

**Comment by kipe** [comment] 2017-08-23 09:50
Hey, coworker of @oh5fsz here.

At least the circumstances you were able to reproduce the bug are very similar to ours. All the four points match to the typical situation, when we experienced this. We also haven't figured out a proper way to reproduce this, all I can say that with versions below 1.3.0 this doesn't seem to happen for one reason or another.

**Comment by PierreF** [comment] 2017-08-23 17:09
Found how to reproduce this issue. The following script fail:
```
import paho.mqtt.client

def _on_connect(client, userdata, flags, rc):
    if rc == 0:
        for msg in userdata:
            client.publish(*msg)


def _on_publish(client, userdata, mid):
    client.disconnect()


def main():
    msgs = []
    for _ in range(21):
        msgs.append((
            'topic',
            b'payload',
            1,  # QoS == 1
            False,  # don't retain
        ))

    client = paho.mqtt.client.Client(userdata=msgs)
    client.on_publish = _on_publish
    client.on_connect = _on_connect
    client.connect('127.0.0.1', 1884, 60)
    client.loop_forever()


if __name__ == '__main__':
    main()
```

What happens:

* it publish more than 20 message (client._max_inflight_messages)
* it disconnect when the first message get its puback.
* in [_do_on_publish](https://github.com/eclipse/paho.mqtt.python/blob/f53da37ce6305f4be081106c46942112465f52be/src/paho/mqtt/client.py#L2549), because the message was a QoS > 0 we call _update_inflight
* _update_inflight will find a message to be sent (because we queued 21 messages, more than client._max_inflight_messages). This will do a call to _send_publish -> _packet_queue -> loop_write!
* loop_write will (in my case) sent the disconnect and therefor close the socket :(
* Now remember than all our calls started from loop_read() than received one puback. It expect 20 puback and will there try to read the next one... from the closed socket.

At the ends, this was caused by disconnect() being called while some messages are still waiting.

@kipe or @oh5fsz : in your case, you don't call disconnect() right ? That still could be explained by nearly the same cause. Just that loop_write() close the socket because of an network error (timeout, connection broken...) instead of user initiated disconnect().
So this bug should happen when:
* More than 20 message with QoS > 0 are queued
* Network cause some error (timeout, ...)

**Comment by kipe** [comment] 2017-08-24 05:46
@PierreF No, we don't call disconnect. There may very well be a lot of messages in QoS 2 -level, as we're sending data ~every 5 seconds. Also the network connections are often quite poor, so this seems like a probable cause.

**Comment by fabiocapsouza** [comment] 2017-09-15 01:42
I just encountered the same issue here. The device is connected to an intermittent WiFi connection and sending only QoS 1 and 2 messages. It happened after the connection was lost for some minutes. After this error the process couldn't send or receive any messages.

**Comment by PierreF** [comment] 2017-09-29 09:36
Committed on fixes branch a test to avoid this crash.

**Closed by PierreF** 2017-09-29 09:36 UTC
