### ISSUE TITLE
paho-mqtt 1.2.1 breaks publishing to AWS IoT service

### ISSUE THREAD

**Issue by rvandegrift** [eclipse/paho.mqtt.python#172] opened 2017-04-03 18:09 UTC
With paho-mqtt 1.2, I use something like this to publish messages on the AWS IoT service:
```python
paho.mqtt.publish.single(
    topic='my/topic',
    client_id='my_client_id',
    payload='{"my": "payload"}',
    hostname='data.iot.us-east-1.amazonaws.com',
    port=8883,
    tls={
        'tls_version': ssl.PROTOCOL_TLSv1_2,
        'ca_certs': 'ca.pem',
        'certfile': 'cert.pem',
        'keyfile': 'private.pem',
        'cert_reqs': ssl.CERT_REQUIRED,
    }
)
```

Using 1.2.1 with the same credentials & policy, the messages never appear on the IoT service.

**Comment by PierreF** [comment] 2017-04-04 09:48
I've an idea of the bug. It was introduced by #119.

The first message is published before connecting to MQTT, which is not an issue with QoS=1 or 2 (message is queued). But with QoS = 0, the first message is discarded.

**Comment by rvandegrift** [comment] 2017-04-04 15:09
Makes sense, and I can confirm using qos=1 works (AWS IoT doesn't support qos=2).

**Comment by PierreF** [comment] 2017-04-10 17:50
I've committed a fix on fixes branch and added test for that issue.

@ralight should we do another 1.2.2 release for that regression ?

**Comment by ralight** [comment] 2017-04-10 21:50
Definitely.

**Comment by PierreF** [comment] 2017-04-11 07:33
@ralight just pushed and tagged the release on github. I let you push it on PyPI ?

**Comment by ralight** [comment] 2017-04-11 09:32
Great work, I've pushed the updated version to pypi.

**Closed** 2017-04-11 09:35 UTC

**Comment by olgeorge** [comment] 2017-06-02 07:37
@rvandegrift How does AWS IoT support QoS 1? From their documentation:
"The message broker does not support persistent sessions (clean session set to 0). All sessions are assumed to be clean sessions and messages are not stored across sessions. If an MQTT client sends a message with the clean session attribute set to false, the client will be disconnected."
http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

How is QoS 1 possible without not-clean sessions? When a device connects with a clean session you won't get any messages that were sent while it was offline, thus violating QoS 1

**Comment by rvandegrift** [comment] 2017-06-02 14:32
@olgeorge here's my (limited!) understanding: qos and session persistence are mostly orthogonal.  qos=1 requires the client to acknowledge publishes.  A persistent session queues messages with qos > 0.  So the result would be publish acknowledgments, but no way to ensure delivery of messages published while the client was offline.

I haven't dug into the AWS behavior too closely, but qos=1 works with paho-mqtt and I've never seen a message delivered without the client being online.

**Comment by PierreF** [comment] 2017-06-02 14:44
I'll add that even if AWS does not "support" QoS = 1, this issue was about a paho-mqtt bug. The following occurred with or without AWS as broker:

* When client send message using publish helper with QoS = 0, the first message was lost.
* But when client send message using publish helpder with QoS > 0, message were not lost.

In this case, using QoS = 1 was a workaround for this bug. And this workaround is no longer needed since version 1.2.2.
