### ISSUE TITLE
Publish message to a specific client ID

### ISSUE THREAD

**Issue by bcashier** [eclipse/paho.mqtt.python#433] opened 2019-10-28 19:39 UTC
Hi,

Is it possible to publish message to a specific client id ?

I want to publish two things using mqtt:
1- General informations like users scores, stats etc ... and can be viewable by everyone.
2- Sensitive informations reserved for private user like own score, name etc ...

Is there any clean way to do it using Paho MQTT ?

Thank you

**Comment by mbenabda** [comment] 2020-04-16 19:38
MQTT is pub/sub. point to point messaging can be achieved but is not what the protocol was designed for.
You could publish an encrypted payload to a topic that is specific to your recipient (ex: point-to-point/${recipient id}), and setup your broker's access control so that only that recipient is allowed to subscribie to that topic

**Comment by ralight** [comment] 2020-08-07 14:22
I'm closing this issue because you've received a relevant answer above, and it's not related to the Python client particularly. If you disagree, please reopen and provide more details.

**Closed by ralight** 2020-08-07 14:22 UTC
