### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by vitalerter** [eclipse/paho.mqtt.python#574] opened 2021-05-26 12:57 UTC
Hi, the library return error :
on linux: **failed to receive on socket: [Errno 104] Connection reset by peer**
on windows: **failed to receive on socket: [WinError 10054] An existing connection was forcibly closed by the remote host**

extra information:

using with asycnio 
paho-mqtt   1.5.1
broker is Rabbitmq 

`"extra": {
      "interpreter": "/usr/local/bin/python",
      "interpreter_version": "3.8.2",
      "func_name": "_easy_log",
      "process_name": "MainProcess",
      "thread_name": "MainThread",
      "logger_name": "mqtt",
      "path": "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py",
      "logstash_async_version": "2.2.0",
      "line": 2404`

Any idea?
Thanks.

**Comment by ralight** [comment] 2021-07-23 21:00
Have you got a minimal code example that shows the behaviour you are seeing?

**Comment by vitalerter** [comment] 2021-07-26 06:55
I just connect to rabbitmq broker and send message with qos1 every 1 s and receive from 5 topics every 10 ms.
i used asyncio example

**Comment by ralight** [comment] 2021-07-26 11:07
I've tried to reproduce this with rabbitmq 3.8.9 using the loop_asyncio.py example modified to subscibe to the `#` topic at qos 1, and a separate publish example that published on 5 topics every 10ms. It all worked fine for me, so I'm afraid I don't know what to try next.

**Comment by PierreF** [comment] 2024-01-07 16:38
Closed as we can't reproduce the issue. Feel free to reopen if you have more information to reproduce the issue.

**Closed by PierreF** 2024-01-07 16:38 UTC
Labels: Type: Bug, Status: Blocked
