### ISSUE TITLE
publish can't send  payload  to  mqtt

### ISSUE THREAD

**Issue by willisfeng** [eclipse/paho.mqtt.python#526] opened 2020-11-18 12:40 UTC
### ### ### ### ### 
def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.publish("test", payload="hello world", qos=1)
### ### ### ### ### 
def on_message(client, userdata, msg):
    print("Start server!")
    print(msg.topic + " " + str(msg.payload))
### ### ### ### ### 
def on_subscribe(client, userdata, mid, granted_qos):
    print("On Subscribed: qos = %d" % granted_qos)
### ### ### ### ### 
def on_publish(client, userdata, mid):
    print("message ID ", mid)
    #client.disconnect()
### ### ### ### ### 
def on_disconnect(client, userdata, rc):
    if rc != 0:
        print("Unexpected disconnection %s" % rc)
### ### ### ### ### 
def on_log(mqttc, obj, level, string):
    print("Log:"+string)
### ### ### ### ### 
def main():
    client.on_connect = on_connect
    client.on_message = on_message
    client.on_subscribe = on_subscribe
    client.on_publish = on_publish
    client.on_log = on_log
    client.connect(host, int(port), keepalive=60)
    client.loop_forever()
 
----------------------------------------------------------------------------------------------------------------------------------------------
log：
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.ProtocolProcessor   : Processing CONNECT message. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394, username=c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.ProtocolProcessor   : Configuring connection. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.ProtocolProcessor   : The connection has been configured CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394, keepAlive=60, removeTemporaryQoS2=true, idleTime=90
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.ProtocolProcessor   : Sending CONNACK. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.SessionsRepository  : Retrieving session. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.SessionsRepository  : Session does not exist. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.ProtocolProcessor   : CONNACK has been sent. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.BrokerInterceptor   : Sending MQTT CONNECT message to interceptor. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394, interceptorId=com.iot.mqtt.broker.interception.HazelcastDispatchInterceptHandler@_hzInstance_1_dev
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.SessionsRepository  : Retrieving session. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.SessionsRepository  : Session does not exist. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394
2020-11-18 20:32:05.970  INFO [] 9504 --- [nioEventLoopGroup-6-7] io.moquette.spi.impl.SessionsRepository  : Creating new session. CId=3u7b3y65-c1a0b0035240401a92dc434d3954b394, cleanSession=true
`

**Comment by ralight** [comment] 2020-12-08 21:49
I've tested out your code and it works fine, once I added `client = paho.Client()`.

```
Log:Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
Log:Received CONNACK (0, 0)
Connected with result code 0
Log:Sending PUBLISH (d0, q1, r0, m1), 'b'test'', ... (11 bytes)
Log:Received PUBACK (Mid: 1)
message ID  1
```

**Comment by ralight** [comment] 2021-07-22 01:02
I'm going to close this because I think the issue is solved, if you disagree please reopen and provide some more details.

**Closed by ralight** 2021-07-22 01:02 UTC
