### ISSUE TITLE
The protocol property of the Client causes RecursionError

### ISSUE THREAD

**Issue by bjarne-hansen** [eclipse/paho.mqtt.python#826] opened 2024-03-22 23:31 UTC
# Bug Description

The .protocol property causes RecursionError.  I believe the line `return self.protocol` should read `return self._protocol`

```
   @property
    def protocol(self) -> MQTTProtocolVersion:
        """
        Protocol version used (MQTT v3, MQTT v3.11, MQTTv5)

        This property is read-only.
        """
        return self.protocol
```

**Comment by PierreF** [comment] 2024-03-23 07:35
Duplicate of #820

**Closed by PierreF** 2024-03-23 07:35 UTC
Labels: Status: Available
