### ISSUE TITLE
Using TLS v1.2 and client.loop() doesn't receive all MQTT packets

### ISSUE THREAD

**Issue by icedwards** [eclipse/paho.mqtt.python#151] opened 2017-02-14 14:58 UTC
I am connecting to a server which puts multiple MQTT packets in a single TCP packet. I'm using client.loop() to receive messages published to my subscription, and this works just fine if I use a connection which is not secure.

As soon as I attempt to use a secure connection, if the server sends multiple MQTT packets in a single TCP packet, the loop sees the 1st of these MQTT packets only and ignores the rest.

As a workaround, if I set max_packets to something other than 1 (and modify client.py to pass the value through) then the code does work correctly, i.e. it correctly unpacks the MQTT packets and presents them to my on_message callback.

A bit of additional information on this, I'm using TLS v1.2 and have tried running under python 2.7.13 and python 3 with the same result.

**Comment by PierreF** [comment] 2017-02-17 17:41
This strange behavior remind me issue #131. This could be the cause of your problem. If it's the case, it's already fixed in branch fixes by PR #132, but not yet released.

**Comment by icedwards** [comment] 2017-02-20 18:25
Certainly sounds like the same problem. Indeed, the messages in question were retained messages that matched my wildcard topic filter (although, I don't think this is a requirement, just that multiple messages are sent in a single TCP packet).

Any idea when PR #132 will be released?

**Comment by PierreF** [comment] 2017-04-24 09:35
This issue is fixed on develop branch.
The release is expected by end of June.

**Closed by PierreF** 2017-04-24 09:35 UTC
