### ISSUE TITLE
only 120 retained messages delivered immediately after connect

### ISSUE THREAD

**Issue by smurfless1** [eclipse/paho.mqtt.python#428] opened 2019-10-09 21:41 UTC
We have a topic of retained messages of QOS1. Our default connection to log in and subscribe to them is clean=True, no ID, QOS 2. Recently we noticed we're only getting 120 messages, and no more. They're always the earliest 120 messages. Changing to clean=false with an ID does not change it, changing to different subscription QOS levels also does not change it. How do I get the rest of them?

Printing with the mosquitto_sub CLI tool shows the messages are in the topic, so the data is not lost. 

broker is paho-mqtt, client is python paho-mqtt

**Comment by dometec** [comment] 2019-11-13 16:32
same problem here...

**Comment by pkshima** [comment] 2020-06-25 22:13
Exact same issue here. Would really appreciate an update.

**Comment by pkshima** [comment] 2020-06-25 22:23
Found the solution here :-)
https://www.eclipse.org/lists/paho-dev/msg04335.html

**Comment by MattBrittan** [comment] 2024-01-07 22:23
I'm going to close this due to it's age and lack of reproducibility (sorry that no one working on the project has responded previously).

If you are still encountering this issue then please feel free to reopen it; however we would appreciate additional details to enable us to identify/replicate the issue i.e.

* Subscribe with the same pattern using `mosquitto_sub` and show a summary of the output (from your question it's unclear if `mosquitto_sub` retrieves all of the retained messages successfully or if you are just testing with more specific patterns)
* Mosquitto version, config and, ideally, logs
* A minimal version of your code (so we can see how you are connecting, subscribing, and handling the messages.

This kind of issue can be difficult to track down; often it's a server configuration issue (as noted by @pkshima).

**Closed by MattBrittan** 2024-01-07 22:23 UTC
