### ISSUE TITLE
limit of 1024 connections

### ISSUE THREAD

**Issue by whyameye** [eclipse/paho.mqtt.python#183] opened 2017-04-16 23:18 UTC
Use of `select` in `client.py` line 908 forces a limitation of 1024 connections, at least on Linux machines. Furthermore, when the limit is reached it is not reported because it is intercepted by line 912 (`ValueError`).

See http://stackoverflow.com/questions/14250751/how-to-increase-filedescriptors-range-in-python-select/14250961#14250961 for more information on the connection limit of `select`

**Comment by swails** [comment] 2017-04-17 03:07
This is true of a lot more than just Python.  For instance, if you run a `mosquitto` broker on a Linux host that has the default fd limit (set to 1024), you won't be able to sustain more than 1024 client connections.

`poll` is troubling since it claims in the Python documentation *not* to be cross-platform and isn't available on all operating systems.  I see no such warning for `select.select()`.  Perhaps I'm mistaken, but I've gotten the impression that the understanding of the open file descriptor limit in the context of MQTT was fairly well-understood.

Is there a reason you can't just up the fd limit on your Linux box?

**Comment by whyameye** [comment] 2017-04-17 03:33
If by fd limit you mean the limit reported by ulimit -n that does not solve the problem in this case.

**Comment by PierreF** [comment] 2017-04-17 15:50
Yes, there is indeed an issue with select.select() that only accept FD whose number below 1024 (at least on linux).
Since this is a client library, you're usually connecting only to one server. To better prioritize issue could you describe the use case that cause to reach more than 1024 connection on an MQTT client ?

For a possible fix, a look to [selectors](https://docs.python.org/3/library/selectors.html) module could be an easy solution to use the best method between select/epoll/kqueue...

**Comment by whyameye** [comment] 2017-04-17 16:20
For me the issue isn't how many servers you connect to but how many connections you can make to the same server. My use case is a bench mark or a stress test. At the least, if an error were reported it would be helpful.

**Comment by PierreF** [comment] 2017-04-17 16:32
Ok understood.
As workaround you should keep ulimit -n to 1024, which will generate an error. Using multiple process could allow to go further than... about 340 connection (because a pipe - so 2 FD - is created with each connection).

**Comment by MattBrittan** [comment] 2023-12-07 20:29
I'm going to close this as a duplicate of #238 (I realise that this issue was raised earlier but #238 has significantly more content and more recent activity so seems best to focus on that going forward). This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).

**Closed by MattBrittan** 2023-12-07 20:29 UTC
