### ISSUE TITLE
loop_forever() hides exceptions

### ISSUE THREAD

**Issue by jbnjohnathan** [eclipse/paho.mqtt.python#504] opened 2020-07-31 13:13 UTC
paho-mqtt==1.5.0

I am using the loop_forever() funktion to do some things when an message which I subscribe to is found.

```
def on_message():
    doing stuff

mqtt_client.on_message = on_message
mqtt_client.loop_forever()
```

However if there are issues in the `on_message()` function that throws exceptions, those are not shown, instead they are eaten and kept secret by the `loop_forever()`
This is causing a lot of issues for me. Is there a way to let the loop allow exceptions and crash the python script instead of staying silent?

**Comment by ralight** [comment] 2020-08-07 13:50
You're quite right. This is a duplicate of #365 with a new PR in #507, so I hope it's ok if I close this particular issue.

**Closed by ralight** 2020-08-07 13:50 UTC
