### ISSUE TITLE
Websocket over TLS can't send message larger than 16384 bytes

### ISSUE THREAD

**Issue by calebhalvy** [eclipse/paho.mqtt.python#248] opened 2017-11-20 21:05 UTC
I have tls set and am connecting using websockets to the broker, but can't send messages that are very large, i.e. > 16384(2^14) bytes. When I don't set connection as secure, the messages send. I get an errno 11 inside _buffered_read in client.py at 
` if len(data) < wanted_bytes:
        raise socket.error(errno.EAGAIN, 0)`

**Comment by PierreF** [comment] 2017-11-26 12:50
I can't reproduce this issue. I'm able to send and receive message up to 1 Mb over TLS websocket.
Could you provide more information ? The full traceback will help.
More details on what you are doing may also help (I'm not sure to see why *sending* message cause an error on a *read* function), ideally a small example that exhibit this issue.

**Comment by larshesel** [comment] 2018-01-29 10:45
Hi,

Not 100% sure this is related, but we had a similar issue, but the problem was when the websocket payload encoding was between 32768  and 65535. This seems to be an issue here:

 https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L2805-L2814

Particularly the `elif length < 32768` case as the spec states: `Note that in all cases, the minimal number of bytes MUST be used to encode the length` and as we can encode values up to 16 bits using the 7 bits (val 126) + 16 bit encoding we should use that instead of the 64 bit encoding to conform to the spec.

I'll create a PR for this case in a bit.

**Comment by larshesel** [comment] 2018-01-30 07:11
yeah, I could imagine most websocket server implementations would be lenient about this particular part of the spec. I experienced this problem using the websocket implementation in the Cowboy web-server which we use in VerneMQ.

**Comment by ralight** [comment] 2021-07-25 21:27
I've not been able to reproduce the problem with the fix from #267, so I'm closing this. If it's still a problem, please reopen.

**Closed by ralight** 2021-07-25 21:27 UTC
