### ISSUE TITLE
connect does not return

### ISSUE THREAD

**Issue by refigh** [eclipse/paho.mqtt.python#456] opened 2020-01-10 13:41 UTC
Hello,
when the server is not available, the client call to connect, gets stuck there, and does not return. When the server becomes available again, it does not continue.
In those situations, I also see "Error <class 'socket.timeout;> occurred, but not sure it is related to this.
Any idea to solve this?

**Comment by MattBrittan** [comment] 2023-12-24 02:26
I'm going to close this due to it's age and lack of a reproducible example/logs. At a minimum please share your code.

**Closed by MattBrittan** 2023-12-24 02:26 UTC
