### ISSUE TITLE
out of memory crash + disconnection in exit of context manager when using qos=2 (paho 1.3.1)

### ISSUE THREAD

**Issue by axd1967** [eclipse/paho.mqtt.python#250] opened 2017-11-25 21:01 UTC
for some dark reason, an out of memory error + disconnection occurs when publishing a qos=2 message.

I've created a small Vagrant VM that runs a RabbitMQ config and a client that attempts to send such a message:  https://github.com/axd1967/paho-bug

the bug seems to happen upon exit of a context manager in  publish() in paho/mqtt/client.py(1121):
https://github.com/eclipse/paho.mqtt.python/blob/e9914a759f9f5b8081d59fd65edfd18d229a399e/src/paho/mqtt/client.py#L1121

(note: code simplified, I can successfully send qos=0 and qos=1 messages via RabbitMQ)

paho-mqtt (1.3.1) , Ubuntu 16

**Comment by axd1967** [comment] 2017-11-27 07:41
hmmm... just noticed - could this be due to RabitMQ MQTT plugin not dealing with QoS=2?
see top of  https://www.rabbitmq.com/mqtt.html

**Comment by axd1967** [comment] 2017-11-27 17:17
hmmm... just noticed - could this be due to RabitMQ MQTT plugin not dealing with QoS=2?
see top of  https://www.rabbitmq.com/mqtt.html

**Comment by axd1967** [comment] 2017-12-01 15:51
Aha! Maybe this is part of the issue:

https://groups.google.com/forum/#!searchin/rabbitmq-users/mqtt$20qos$3D2|sort:date/rabbitmq-users/AVKOnNzX_7w/NEiYB6zICQAJ

**Comment by PierreF** [comment] 2017-12-04 09:54
Thank for your patience and report detailed report.

RabbitMQ don't like QoS=2 package, but on my quick test (docker run rabbitmq, then rabbitmq-plugins enable rabbitmq_mqtt) I don't reproduce an out of memory. The client only get disconnected as soon as it publish the message and reconnect (in loop). Which is expected if the broker don't support them :)

I will try to test you Vagrant file in the next days.

**Comment by axd1967** [comment] 2017-12-04 11:58
(edit added: Ubuntu 16)

**Comment by PierreF** [comment] 2017-12-06 17:55
Are you saying you have out of memory because the disconnect error is "Out of memory." ?
There is no out-of-memory in this cause, just a wrong number for this error :)

This come from https://github.com/eclipse/paho.mqtt.python/blob/e9914a759f9f5b8081d59fd65edfd18d229a399e/src/paho/mqtt/client.py#L1794 which use "1" instead of an MQTT_ERR_XXX.

So except for a wrong error message, there is no other issue.

**Comment by axd1967** [comment] 2017-12-15 22:13
did you try the Vagrant approach?

I crafted it specially, the README explains the steps to reproduce the issue. 

why does a disconnection happens? it looks like qos=2 is not correctly dealt with.

**Comment by PierreF** [comment] 2017-12-15 22:23
What I reproduce is RabbitMQ closing the connection (because it don't support QoS=2). On the client side I don't see any bad behavior (except the message / return code which is not the good one).

That why I asked if the "Out of memory" come only from the error_string(result). If that the case, the only issue on paho side is that a return 1 is used for a generic error, but MQTT_ERR_NOMEM also have the value 1. Paho should be updated to return a most useful error.

Paho can't do anything better with QoS=2 and RabbitMQ, the broker don't support it and you should either use only QoS < 2 or use another broker.

**Comment by YoungPyDawan** [comment] 2021-10-04 09:23
At least issue from 
https://github.com/eclipse/paho.mqtt.python/issues/250#issuecomment-349722293
is fixed in 1.6 branch:
https://github.com/eclipse/paho.mqtt.python/blame/1.6.x/src/paho/mqtt/client.py#L2373

by commit https://github.com/eclipse/paho.mqtt.python/commit/332834e7ec293f1bfe385180b8691863af5a7738
so close?

**Comment by ralight** [comment] 2021-10-04 10:09
I think so, yes, thanks for flagging this.

**Closed by ralight** 2021-10-04 10:09 UTC
