### ISSUE TITLE
 error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by wangchengpei** [eclipse/paho.mqtt.python#523] opened 2020-11-05 03:21 UTC
Traceback (most recent call last):
  File "/home/worker/compass/vehicle_backend/web_service/extensions/redis_subscriber.py", line 56, in handle_msg
    MQTT_CLIENT.publish(Topic.TRACKING, data)
  File "/home/worker/compass/vehicle_backend/web_service/extensions/mqtt_client.py", line 143, in publish
    self._publish(mqtt_topic, payload)
  File "/home/worker/compass/vehicle_backend/utils/mqtt_client_base.py", line 92, in _publish
    self.__client.publish(topic, payload)
  File "/home/worker/compass/depends/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1270, in publish
    local_mid, topic, local_payload, qos, retain, False, info, properties)
  File "/home/worker/compass/depends/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2580, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/home/worker/compass/depends/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 2927, in _packet_queue
    self._sockpairW.send(sockpair_data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by BertKleewein** [comment] 2021-04-06 16:58
May have the same root cause as #563.  Without more detail, it is impossible to know.

**Comment by MattBrittan** [comment] 2024-01-06 04:01
Closing this as it's probably a duplicate of #563 (which is resolved) and without more info it would not be possible to really know.

Please feel free to reopen with more details (after testing against the latest release).

**Closed by MattBrittan** 2024-01-06 04:01 UTC
