### ISSUE TITLE
I use my server pub a info. I sub it.But i can not receive it.

### ISSUE THREAD

**Issue by pengbo19921206** [eclipse/paho.mqtt.python#323] opened 2018-08-10 01:33 UTC
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2010-2013 Roger Light <roger@atchoo.org>
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Distribution License v1.0
# which accompanies this distribution.
#
# The Eclipse Distribution License is available at
#   http://www.eclipse.org/org/documents/edl-v10.php.
#
# Contributors:
#    Roger Light - initial implementation
# Copyright (c) 2010,2011 Roger Light <roger@atchoo.org>
# All rights reserved.

# This shows a simple example of an MQTT subscriber.

#import context  # Ensures paho is in PYTHONPATH
import paho.mqtt.client as mqtt


def on_connect(mqttc, obj, flags, rc):
    print("rc: " + str(rc))


def on_message(mqttc, obj, msg):
    print(msg.topic + " " + str(msg.qos) + " " + str(msg.payload))


def on_publish(mqttc, obj, mid):
    print("mid: " + str(mid))


def on_subscribe(mqttc, obj, mid, granted_qos):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))


def on_log(mqttc, obj, level, string):
    print(string)


# If you want to use a specific client id, use
# mqttc = mqtt.Client("client-id")
# but note that the client id must be unique on the broker. Leaving the client
# id parameter empty will generate a random id for you.
mqttc = mqtt.Client()
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.on_subscribe = on_subscribe
# Uncomment to enable debug messages
# mqttc.on_log = on_log
mqttc.connect("my server", 1883, 60)
mqttc.subscribe("test", 0)

mqttc.loop_forever()
```

**Comment by PierreF** [comment] 2018-09-02 09:28
I don't see any issue with your code.
How did you publish the message ? Is the message published *after* the subscribe is done ?

If you could attach log from the client (uncomment the mqttc.on_log = on_log to get them) and ideally also your broker (if it's mosquitto, start it in verbose mode with -v option).

**Comment by PierreF** [comment] 2018-09-02 09:30
Closing a duplicate of #322. Please continue on #322 thread.

**Closed by PierreF** 2018-09-02 09:30 UTC
